name: Rust

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
